<a href="https://colab.research.google.com/github/thao1105/Thanhthao/blob/main/BTVN_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bài 1 

In [2]:
x = []
print("Mời bạn nhập lần lượt 7 phần tử x")
for i in range (0,7,1):
  x.append(int(input()))
print(x) 


Mời bạn nhập lần lượt 7 phần tử x
0
1
2
3
4
5
6
[0, 1, 2, 3, 4, 5, 6]


Bài 2



In [ ]:
import random
x = []
for i in range (0,30,1):
  x = (random.randint(-10,10))
print("random number between -10 and 10 is % d" % (x))

random number between -10 and 10 is -2


Bài 3 

In [ ]:
import random 
x = []
for i in range (0,30,1):
  x.append(random.uniform(-5.7,6.9))
print(x)

[1.1546000025848775, -5.621184694735252, 6.351870341228271, -4.117266948642994, 2.350126786357033, 3.183566836160046, 2.8487903194013606, -0.20060979782984845, -0.36240544290998855, -5.393756576365821, 0.3225910804624377, 6.252992438117906, -4.411471488143585, 0.508222082542793, 1.4852571287570173, 2.47995823133635, 5.285182674797414, 1.9509381539405357, 5.267055064544752, 0.929486500629924, 3.5734821706258417, -2.0958220930472584, -0.9219360546346129, -3.0685500752719554, 6.428083269470249, -3.933997994123959, 6.861458771778504, -1.792024909370423, 0.7777545967340957, -1.5760282320776389]


Bài 4 

In [9]:
import random
x = []
x1 = []
a = int(input("Nhập phần tử của a = "))
for i in range (0,10,1):
  x.append(random.randint(-10,10))
  x1.append(x[i]*a)
print("vector x được sinh ngẫu nhiên :",x)
print("Nhân số với vector",x1)

Nhập phần tử của a = 4
vector x được sinh ngẫu nhiên : [-7, 10, -10, 8, -1, 8, 7, 0, 10, 1]
Nhân số với vector [-28, 40, -40, 32, -4, 32, 28, 0, 40, 4]


Bài 5 

In [11]:
import random 
x = []
y = []
x3 = []
x4 = []
for i in range(0,15,1):
    x.append(random.randint(-20, 20))
    y.append(random.randint(-20, 20))
    x3.append(x[i]+y[i])
    x4.append(x[i]-y[i])
print("vector x được sinh ngẫu nhiên :",x)
print("vector y được sinh ngẫu nhiên :",y)
print("Phép cộng của 2 vector x, y :",x3)
print("Phép trừ của 2 vector x, y :",x4)

vector x được sinh ngẫu nhiên : [-12, 14, -5, 3, -13, -4, -11, -13, -14, 18, 6, -3, 15, 13, -8]
vector y được sinh ngẫu nhiên : [11, 10, 18, 8, -16, -11, -2, -18, -20, -5, -14, 15, 18, -1, 0]
Phép cộng của 2 vector x, y : [-1, 24, 13, 11, -29, -15, -13, -31, -34, 13, -8, 12, 33, 12, -8]
Phép trừ của 2 vector x, y : [-23, 4, -23, -5, 3, 7, -9, 5, 6, 23, 20, -18, -3, 14, -8]


Bài 6 

In [25]:
import random 
import numpy as np
x =[]
y = []
phep_nhan = []
for i in range(0,10,1):
    x.append(random.randint(-10, 10))
    y.append(random.randint(-10,10))
    phep_nhan= np.multiply(x , y)
print("vector x được sinh ngẫu nhiên :",x)
print("vector y được sinh ngẫu nhiên :",y)
print("phép nhân elementwise multiplication x*y :",phep_nhan)

vector x được sinh ngẫu nhiên : [3, 0, -2, 8, 9, -10, 6, -8, 2, -1]
vector y được sinh ngẫu nhiên : [2, -4, 3, 3, -2, -4, 5, 10, 7, -5]
phép nhân elementwise multiplication x*y : [  6   0  -6  24 -18  40  30 -80  14   5]


Bài 7 

In [34]:
import random
import numpy as np
x = []
y = []
T_V_H = 0 
for i in range (0,10,1):
    x.append(random.randint(-10,10))
    y.append(random.randint(-10,10))
    T_V_H += (x[i]*y[i])
print(x)
print(y)
print("Tích vô hướng của 2 vector x, y :",T_V_H)

[-2, -2, -5, -9, -4, 2, 7, 4, 7, 5]
[0, 4, -10, 10, 0, -9, 10, -2, 2, 4]
Tích vô hướng của 2 vector x, y : 30


Bài 8 

In [65]:
import numpy as np
import random 
x = []
x = np.random.randint(-10,10,size = (3,5))
print(x)
print("phần tử a23 :",x[1,2])

[[  4  -1 -10   2   6]
 [ -5  -4  -9   3  -6]
 [  6   6   3   7  -9]]
phần tử a23 : -9


Bài 9 

In [69]:
import numpy as np
import random
a = int(input("Mời bạn nhập số a = "))
for i in range(0,10,1):
  x = np.random.randint(-10,10,size = (3,5))
print(x)
print("Phép nhân vô hướng với ma trận A:",a*x)



Mời bạn nhập số a = 8
[[ 1  9  3 -7 -9]
 [ 3 -7 -8 -8  3]
 [-9  8 -8  3  4]]
Phép nhân vô hướng với ma trận A: [[  8  72  24 -56 -72]
 [ 24 -56 -64 -64  24]
 [-72  64 -64  24  32]]


Bài 10 

In [ ]:
import random 
import numpy as np 
for i in range (0,10,1):
  A=np.random.randint(-10,10,size = (3,5))
  B=np.random.randint(-10,10,size = (3,5))
print(A)
print(B)
print(A+B)


[[-10  -7  -6  -7   5]
 [ -2  -9   1   5   4]
 [ -6  -3  -7  -5   0]]
[[  4   1  -8   9  -4]
 [ -3   2 -10   4  -1]
 [  6  -8 -10   2  -7]]
[[ -6  -6 -14   2   1]
 [ -5  -7  -9   9   3]
 [  0 -11 -17  -3  -7]]


Bài 11 

In [ ]:
import random 
import numpy as np 
for i in range(0,10,1):
  A=np.random.randint(-10,10,size = (3,4))
  B=np.random.randint(-10,10,size = (4,5))
print(A)
print(B)
print(A@B)

[[ 8 -8 -1  4]
 [ 2  2 -2  9]
 [ 6 -1  8  5]]
[[  1   1  -8  -7   5]
 [  7 -10   8   1  -4]
 [-10   0   6   3   9]
 [  1 -10  -7   0   1]]
[[ -34   48 -162  -67   67]
 [  45 -108  -75  -18   -7]
 [ -76  -34  -43  -19  111]]
