<a href="https://colab.research.google.com/github/thao1105/Thanhthao/blob/main/BTVN_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bài 1 

In [ ]:
x = []
print("Mời bạn nhập lần lượt 7 phần tử x")
for i in range (0,7,1):
  x.append(int(input()))
print(x) 


Mời bạn nhập lần lượt 7 phần tử x
8
0
2
5
1
3
7
[8, 0, 2, 5, 1, 3, 7]


Bài 2



In [ ]:
import random
x = []
for i in range (0,30,1):
  x = (random.randint(-10,10))
print("random number between -10 and 10 is % d" % (x))

random number between -10 and 10 is -2


Bài 3 

In [ ]:
import random 
x = []
for i in range (0,30,1):
  x.append(random.uniform(-5.7,6.9))
print(x)

[1.1546000025848775, -5.621184694735252, 6.351870341228271, -4.117266948642994, 2.350126786357033, 3.183566836160046, 2.8487903194013606, -0.20060979782984845, -0.36240544290998855, -5.393756576365821, 0.3225910804624377, 6.252992438117906, -4.411471488143585, 0.508222082542793, 1.4852571287570173, 2.47995823133635, 5.285182674797414, 1.9509381539405357, 5.267055064544752, 0.929486500629924, 3.5734821706258417, -2.0958220930472584, -0.9219360546346129, -3.0685500752719554, 6.428083269470249, -3.933997994123959, 6.861458771778504, -1.792024909370423, 0.7777545967340957, -1.5760282320776389]


Bài 4 

In [ ]:
import random
x = []
x1 = []
a = int(input("Nhập phần tử của a = "))
for i in range (0,10,1):
  x.append(random.randint(-10,10))
  x1.append(x[i]*a)
print(x)
print(x1)

Nhập phần tử của a = 4
[-4, -10, -3, -7, -10, -4, 4, -8, 2, 4]
[-16, -40, -12, -28, -40, -16, 16, -32, 8, 16]


Bài 5 

In [ ]:
import random 
x1 = []
x2 = []
x3 = []
x4 = []
for i in range(0,15,1):
    x1.append(random.randint(-20, 20))
    x2.append(random.randint(-20, 20))
    x3.append(x1[i]+x2[i])
    x4.append(x1[i]-x2[i])
print(x1)
print(x2)
print(x3)
print(x4)

[6, -15, -5, -13, 6, -16, -20, 16, 8, -6, 1, 5, -9, -5, 18]
[19, 7, 12, -20, -19, 14, -4, -12, 11, 13, -3, 14, -12, 2, 10]
[25, -8, 7, -33, -13, -2, -24, 4, 19, 7, -2, 19, -21, -3, 28]
[-13, -22, -17, 7, 25, -30, -16, 28, -3, -19, 4, -9, 3, -7, 8]


Bài 6 

In [ ]:
import random 
import numpy as np
x1 =[]
x2 = []
x = []
for i in range(0,10,1):
    x1.append(random.randint(-10, 10))
    x2.append(random.randint(-10,10))
    x = np.multiply(x1, x2)
print(x1)
print(x2)
print(x)

[-2, -10, 4, 6, -9, -5, 4, -7, 2, -7]
[-4, 2, -10, -10, 5, -4, -5, -2, -6, -1]
[  8 -20 -40 -60 -45  20 -20  14 -12   7]


Bài 7 

In [ ]:
import random
import numpy as np
x = []
y = []
TVH = 0 
for i in range (0,10,1):
    x.append(random.randint(-10,10))
    y.append(random.randint(-10,10))
    TVH += (x[i]*y[i])
print(x)
print(y)
print(TVH)

[7, -4, -5, 5, 6, 1, 10, -6, 0, 5]
[4, 1, -1, 0, 1, 0, -4, 3, -1, -1]
-28


Bài 8 

In [ ]:
import numpy as np
import random 
x = []
a = np.random.randint(0,10,size = (3,5))
print(a)
print(a[1,2])

[[3 5 8 7 9]
 [2 9 4 0 8]
 [9 5 7 9 8]]
4


Bài 9 

In [6]:
import numpy as np
import random
a = int(input("Mời bạn nhập số a = "))
for i in range(0,10,1):
  x = np.random.randint(-10,10,size = (3,5))
print(x)
print(a*x)



Mời bạn nhập số a = 8
[[-6  1 -7 -8 -4]
 [-6  5 -4 -3  0]
 [-4  3 -4  9 -1]]
[[-48   8 -56 -64 -32]
 [-48  40 -32 -24   0]
 [-32  24 -32  72  -8]]


Bài 10 

In [12]:
import random 
import numpy as np 
for i in range (0,10,1):
  A=np.random.randint(-10,10,size = (3,5))
  B=np.random.randint(-10,10,size = (3,5))
print(A)
print(B)
print(A+B)


[[-10  -7  -6  -7   5]
 [ -2  -9   1   5   4]
 [ -6  -3  -7  -5   0]]
[[  4   1  -8   9  -4]
 [ -3   2 -10   4  -1]
 [  6  -8 -10   2  -7]]
[[ -6  -6 -14   2   1]
 [ -5  -7  -9   9   3]
 [  0 -11 -17  -3  -7]]


Bài 11 

In [18]:
import random 
import numpy as np 
for i in range(0,10,1):
  A=np.random.randint(-10,10,size = (3,4))
  B=np.random.randint(-10,10,size = (4,5))
print(A)
print(B)
print(A@B)

[[ 8 -8 -1  4]
 [ 2  2 -2  9]
 [ 6 -1  8  5]]
[[  1   1  -8  -7   5]
 [  7 -10   8   1  -4]
 [-10   0   6   3   9]
 [  1 -10  -7   0   1]]
[[ -34   48 -162  -67   67]
 [  45 -108  -75  -18   -7]
 [ -76  -34  -43  -19  111]]
