<a href="https://colab.research.google.com/github/thao1105/Thanhthao/blob/main/B%C3%A0i_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Sinh ngẫu nhiên 1 vector x ∈ R



In [ ]:
import numpy as np
import random
a = np.random.randint(1,10,size=10)
print(a)

[3 5 1 5 1 2 4 1 2 5]


In [ ]:
a = [3 ,5 ,1, 5 ,1, 2 ,4, 1 ,2, 5]
x = np.array(a)
print(np.sin(x))

[ 0.14112001 -0.95892427  0.84147098 -0.95892427  0.84147098  0.90929743
 -0.7568025   0.84147098  0.90929743 -0.95892427]


In [ ]:
a =[3 ,5 ,1, 5 ,1, 2 ,4, 1 ,2, 5]
x = np.array(a)
print(np.cos(x))

[-0.9899925   0.28366219  0.54030231  0.28366219  0.54030231 -0.41614684
 -0.65364362  0.54030231 -0.41614684  0.28366219]


In [ ]:
a = [3 ,5 ,1, 5 ,1, 2 ,4, 1 ,2, 5]
x = np.array(a)
print(np.sqrt(x))

[1.73205081 2.23606798 1.         2.23606798 1.         1.41421356
 2.         1.         1.41421356 2.23606798]


In [ ]:
a =[3 ,5 ,1, 5 ,1, 2 ,4, 1 ,2, 5]
x = np.array(a)
print(np.log10(x))

[0.47712125 0.69897    0.         0.69897    0.         0.30103
 0.60205999 0.         0.30103    0.69897   ]


In [ ]:
import numpy as np
a = np.array([ 0.14112001,-0.95892427,0.84147098,-0.95892427,0.84147098,0.90929743,-0.7568025,0.84147098,0.90929743,-0.95892427])
print(np.round(a))
print(np.round(a, decimals = 2))

a = np.array([-0.9899925,0.28366219,0.54030231,0.28366219,0.54030231,-0.41614684,-0.65364362,0.54030231,-0.41614684,0.28366219])
print(np.round(a))
print(np.round(a, decimals = 2))

a = np.array([1.73205081,2.23606798,1.,2.23606798,1.,1.41421356,2.,1.,1.41421356,2.23606798])
print(np.round(a))
print(np.round(a, decimals = 2))             

a = np.array([1.09861229,1.60943791,0.,1.60943791,0.,0.69314718,1.38629436,0.,0.69314718,1.60943791])
print(np.round(a))
print(np.round(a, decimals = 2))  

[ 0. -1.  1. -1.  1.  1. -1.  1.  1. -1.]
[ 0.14 -0.96  0.84 -0.96  0.84  0.91 -0.76  0.84  0.91 -0.96]
[-1.  0.  1.  0.  1. -0. -1.  1. -0.  0.]
[-0.99  0.28  0.54  0.28  0.54 -0.42 -0.65  0.54 -0.42  0.28]
[2. 2. 1. 2. 1. 1. 2. 1. 1. 2.]
[1.73 2.24 1.   2.24 1.   1.41 2.   1.   1.41 2.24]
[1. 2. 0. 2. 0. 1. 1. 0. 1. 2.]
[1.1  1.61 0.   1.61 0.   0.69 1.39 0.   0.69 1.61]


In [17]:
import numpy as np 
import random 
from math import sin,cos,log,sqrt,tan
A = np.random.randint(low=5, high=10,
size=15).reshape((3,5))
print("ma trận A :")
print(A)
x = np.array(A)
print("sin(A):")
print(np.round(np.sin(x),3))
print("cos(A):")
print(np.round(np.cos(x),3))
print("tan(A):")
print(np.round(np.tan(x),3))
print("căn bậc hai của A :")
print(np.round(np.sqrt(x),3))
print("log(A)")
print(np.round(np.log10(x),3))


ma trận A :
[[5 8 6 7 8]
 [7 8 8 5 9]
 [8 5 7 8 9]]
sin(A):
[[-0.959  0.989 -0.279  0.657  0.989]
 [ 0.657  0.989  0.989 -0.959  0.412]
 [ 0.989 -0.959  0.657  0.989  0.412]]
cos(A):
[[ 0.284 -0.146  0.96   0.754 -0.146]
 [ 0.754 -0.146 -0.146  0.284 -0.911]
 [-0.146  0.284  0.754 -0.146 -0.911]]
tan(A):
[[-3.381 -6.8   -0.291  0.871 -6.8  ]
 [ 0.871 -6.8   -6.8   -3.381 -0.452]
 [-6.8   -3.381  0.871 -6.8   -0.452]]
căn bậc hai của A :
[[2.236 2.828 2.449 2.646 2.828]
 [2.646 2.828 2.828 2.236 3.   ]
 [2.828 2.236 2.646 2.828 3.   ]]
log(A)
[[0.699 0.903 0.778 0.845 0.903]
 [0.845 0.903 0.903 0.699 0.954]
 [0.903 0.699 0.845 0.903 0.954]]


In [20]:
import numpy as np
from math import sin , cos
def ham_bac_2(a,b,c,x):
    result = 3*x*x - 2*x - 4 
    return result 
f = np.linspace(-100,100,1000)
print(f)
print(np.cos(f))
print(np.sin(f))


[-100.          -99.7997998   -99.5995996   -99.3993994   -99.1991992
  -98.998999    -98.7987988   -98.5985986   -98.3983984   -98.1981982
  -97.997998    -97.7977978   -97.5975976   -97.3973974   -97.1971972
  -96.996997    -96.7967968   -96.5965966   -96.3963964   -96.1961962
  -95.995996    -95.7957958   -95.5955956   -95.3953954   -95.1951952
  -94.99499499  -94.79479479  -94.59459459  -94.39439439  -94.19419419
  -93.99399399  -93.79379379  -93.59359359  -93.39339339  -93.19319319
  -92.99299299  -92.79279279  -92.59259259  -92.39239239  -92.19219219
  -91.99199199  -91.79179179  -91.59159159  -91.39139139  -91.19119119
  -90.99099099  -90.79079079  -90.59059059  -90.39039039  -90.19019019
  -89.98998999  -89.78978979  -89.58958959  -89.38938939  -89.18918919
  -88.98898899  -88.78878879  -88.58858859  -88.38838839  -88.18818819
  -87.98798799  -87.78778779  -87.58758759  -87.38738739  -87.18718719
  -86.98698699  -86.78678679  -86.58658659  -86.38638639  -86.18618619
  -85.98598