<a href="https://colab.research.google.com/github/thao1105/Thanhthao/blob/main/th%C6%B0_vi%E1%BB%87n_vector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bài 1 

In [ ]:
import numpy as np 

Bài 2

In [ ]:
import numpy as np 
v1 = np.arange(15, dtype=int)
v2 = np.arange(start=-5, stop =
10, dtype=int)
print(v1)
print(v2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[-5 -4 -3 -2 -1  0  1  2  3  4  5  6  7  8  9]


Bài 3

In [ ]:
import numpy as np 
v3 = np.linspace(start=-2,stop=3,num=15,dtype=float)
print(v3)

[-2.         -1.64285714 -1.28571429 -0.92857143 -0.57142857 -0.21428571
  0.14285714  0.5         0.85714286  1.21428571  1.57142857  1.92857143
  2.28571429  2.64285714  3.        ]


Bài 4

In [ ]:
import numpy as np 
import random
np.random.seed(123)
v4 = np.random.randint(2, size=10)
print(v4)
v5 = np.random.randint(low=-3,high=3, size=10)
print(v5)

[0 1 0 0 0 0 0 1 1 0]
[ 0 -2 -2 -3 -2 -2 -3 -3 -2  0]


Bài 5


In [ ]:
v6 = np.random.random_sample(10)
print(v6)
a =-3
b = 4
v5 = (b -a)*np.random.random_sample(10) + a
print(v5)

[0.28270293 0.43341824 0.00975735 0.34079598 0.68927201 0.86936929
 0.26780382 0.45674792 0.26828131 0.8370528 ]
[-1.10639735  0.71043408 -1.77239137 -0.79523488  3.23776367 -1.73764602
  0.46021342 -1.51391328  0.64613808 -1.8793004 ]


Bài 6 

Vector các số nguyên có n phần tử
và có giá trị tăng dần từ a đến b

In [ ]:
import numpy as np 
a = np.arange(10,dtype=int)
print(a)

[0 1 2 3 4 5 6 7 8 9]


Vector các số thực có n phần tử và
có giá trị tăng dần từ c đến d;

In [ ]:
import numpy as np 
a = np.linspace(-3,2,num=15,dtype=float)
print(a)

[-3.         -2.64285714 -2.28571429 -1.92857143 -1.57142857 -1.21428571
 -0.85714286 -0.5        -0.14285714  0.21428571  0.57142857  0.92857143
  1.28571429  1.64285714  2.        ]


Vector ngẫu nhiên các số nguyên n
phần tử có giá trị trong [a,b];

In [ ]:
import numpy as np 
import random 
a = np.random.randint(-2,3,size = 10)
print(a)

[ 2  2  1  2  1 -2  2  2  2  2]


Vector ngẫu nhiên các số thực n
phần tử có giá trị trong [c,d].

In [ ]:
import numpy as np
import random 
c = 2
d = 3
a =(d-c)*np.random.random_sample(size=10) + c 
print(a)

[2.6917018  2.15112745 2.39887629 2.2408559  2.34345601 2.51312815
 2.66662455 2.10590849 2.13089495 2.32198061]


Bài 7

In [ ]:
print(v5.shape)
print(v5.ndim)

(10,)
1


PHÉP TOÁN 

Bài 1 

In [ ]:
import random 
x = []
x1 = []
a = int(input("Nhập a = "))
for i in range(0,10,1):
  x.append(random.randint(-10,10))
  x1.append(x[i]*a)
print(x)
print(x1)

Nhập a = 8
[-5, -3, 1, -5, -7, -6, 2, -4, 7, 10]
[-40, -24, 8, -40, -56, -48, 16, -32, 56, 80]


Bài 2

In [4]:
import random 
import numpy as np 
x = np.random.randint(5, size=10)
y = np.random.randint(low=-5,high=5, size=10)
z = x + y
print(x)
print(y)
print('z = ', z)

[3 2 1 1 2 3 0 2 0 2]
[ 2 -4 -2  4 -4 -3 -3  0  1  0]
z =  [ 5 -2 -1  5 -2  0 -3  2  1  2]


Bài 3 

In [5]:
import random 
import numpy as np
x = np.random.randint(5, size=10)
y = np.random.randint(low=-
5,high=5, size=10)
print('x = ', x)
print('y = ', y)
n = np.dot(x, y)
print('n = ', n)

x =  [0 4 0 1 1 1 2 0 3 2]
y =  [ 0  2 -2 -3 -5  3 -5 -3  4 -3]
n =  -1


Bài 4

In [6]:
import numpy as np 
import random 
x = np.random.randint(5, size=10)
y = np.random.randint(low=-
5,high=5, size=10)
print('x = ', x)
print('y = ', y)
h = np.multiply(x, y)
print('Hadamard product = ', h)

x =  [1 1 4 1 3 1 3 4 0 0]
y =  [ 2  4 -1 -3  4 -5 -1 -3 -3 -5]
Hadamard product =  [  2   4  -4  -3  12  -5  -3 -12   0   0]
